"""empty message

Revision ID: d0c379fb04b2
Revises: 
Create Date: 2019-11-08 13:29:02.104383

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd0c379fb04b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=49), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=False),
                    sa.Column('password', sa.String(length=128), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('branches',
                    sa.Column('ifsc', sa.String(length=11), nullable=False),
                    sa.Column('branch', sa.String(length=74), nullable=False),
                    sa.Column('address', sa.String(length=195), nullable=True),
                    sa.Column('city', sa.String(length=50), nullable=False),
                    sa.Column('district', sa.String(length=50), nullable=False),
                    sa.Column('state', sa.String(length=26), nullable=False),
                    sa.Column('bank_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
                    sa.PrimaryKeyConstraint('ifsc')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branches')
    op.drop_table('user')
    op.drop_table('banks')
    # ### end Alembic commands ###
